use_frameworks!

platform :ios, '9.0'

pod 'Masonry'

target 'UIKitComponent_Example' do
  pod 'UIKitComponent', :path => '../'

  target 'UIKitComponent_Tests' do
    inherit! :search_paths

    
  end
end
